Is that good to begin with?
codingupastorm/vadersharp pull request #13
Opened 2017-06-17 19:37 UTC by Chr1st1anSzech

I don't know how to determine the actual project folder. Therefore I defined it hard-code. Environment.CurrentDirectory doesn't work in 1.3 So you have to change the path manually.

2017-06-18 14:37 UTC, codingupastorm requested changes
Looks good. Do you want to initialise and actually use the ConfigStore class in this pull req? Or I can put it in later, up to you

2017-06-18 14:37 UTC, codingupastorm commented on VaderSharp/VaderSharp/ConfigStore.cs
> +        public Dictionary<string, double> BoosterDict { get { return boosterDict; } }
Can we do get; private set; here? And other fields in ConfigStore

2017-06-18 16:01 UTC, Chr1st1anSzech commented
Thanks. I'll make a couple of modifications. First of all I wanted to receive a first feedback. Is XML a good choice? Originally, I prefered JSON, however, there's no built-in JSON parser. You would have to use some external framework, e. g. Newtonsoft Json.NET.

2017-06-18 16:07 UTC, codingupastorm commented
I definitely prefer JSON and would be happy to use Json.Net, but you have already put a heap of work in here and I don't think it will have much difference, so we can leave it!

Did you use some code to get the xml file? Even for only some parts of it? It could be useful to include it in a different directory at the top level (utils or scripts or so). I don't think the algorithm or word scores will change, but if they are updated in, say, the original vader in python it would be good to know if there is any useful code to port the new lists across.

2017-06-18 16:19 UTC, Chr1st1anSzech commented
Yeah, JSON has a lesser overhead and I'm sure that it could be parsed faster. I could still change it if it's okay to use such a Framework.

I created the XML file by Hand. Nevertheless it's a good idea to add some methods to add (/remove) words to the list. Or to create the list from a normal (comma separated) text file.

2017-06-22 11:40 UTC, codingupastorm commented
Hey @Chr1st1anSzech you put a heap of work into this so I'm going to merge it and make some changes 🔥 🔥 . Worst case can always keep it as an alternate means of loading the data.

2017-06-22 11:41 UTC, merged